# Site settings
author: G Del Busto
title: Flatiron Blog
header-img: img/home-bg.png
email: gidelbusto@gmail.com
copyright_name: G Del Busto
description: > # this means to ignore newlines until "baseurl:"
  G's Blog
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  GiDeBus

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
