# Site settings
author: immutable-integer-8885
title: 
header-img: img/home-bg.png
email: gidelbusto@gmail.com
copyright_name: immutable-integer-8885
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  GiDeBus

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
